version: '3'

services: 
    odoo:
        image: odoo:12.0
        container_name: Odoo
        restart: always
        links: 
            - db
        ports: 
            - "8069:8069"
    
    db:
        image: postgres:10
        container_name: Postgres
        restart: always
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo